import type { Service } from '../domain/index';
export const FAMILIES: Record<string, { name: string; description: string }> = {
  inspections: {
    name: 'Inspections',
    description: 'A clear record of property condition, presentation and completed work.',
  },
  attendance: {
    name: 'Property attendance',
    description: 'On-site assistance when you need an authorised person at the property.',
  },
  maintenance: {
    name: 'Maintenance & works',
    description: 'Assess reported issues and document repairs and rectification.',
  },
  access: {
    name: 'Access & contractor support',
    description: 'Coordinate authorised access, handovers and contractor attendance.',
  },
  documents: {
    name: 'Documentation',
    description: 'Request property and tenancy documentation with a structured review process.',
  },
  operations: {
    name: 'Ongoing property support',
    description: 'Arrange recurring inspections and operational support for your portfolio.',
  },
};
const all = ['residential', 'commercial', 'strata-building'];
// Reviewed service identities and scheduling defaults from the reference repository.
// No unverified price is imported. Staff must publish operational prices/availability.
const rows: Array<[string, string, string, string[], number, number, string]> = [
  [
    'routine-inspection',
    'Routine Inspection',
    'inspections',
    ['residential'],
    45,
    24,
    'Document the visible condition of a rental property and matters requiring follow-up.',
  ],
  [
    'property-condition-report',
    'Property Condition Report (PCR)',
    'inspections',
    ['residential'],
    90,
    48,
    'Create a detailed photographic incoming condition record for a tenancy.',
  ],
  [
    'pre-vacate-inspection',
    'Pre-Vacate Inspection',
    'inspections',
    ['residential'],
    45,
    24,
    'Identify apparent cleaning, maintenance and rectification matters before a final inspection.',
  ],
  [
    'final-exit-inspection',
    'Final / Exit Inspection',
    'inspections',
    ['residential'],
    60,
    24,
    'Record outgoing property condition and compare available incoming records.',
  ],
  [
    'commercial-property-inspection',
    'Commercial Property Inspection',
    'inspections',
    ['commercial'],
    120,
    48,
    'Inspect commercial premises for visible condition and operational matters.',
  ],
  [
    'commercial-pre-vacate-make-good-inspection',
    'Commercial Pre-Vacate / Make-Good Inspection',
    'inspections',
    ['commercial'],
    90,
    48,
    'Document apparent make-good and handover matters before commercial vacate.',
  ],
  [
    'commercial-final-make-good-inspection',
    'Commercial Final / Make-Good Inspection',
    'inspections',
    ['commercial'],
    90,
    48,
    'Record commercial handover condition and apparent outstanding works.',
  ],
  [
    'common-property-inspection',
    'Common Property Inspection',
    'inspections',
    ['strata-building'],
    60,
    24,
    'Inspect shared areas, accessways and amenities for visible maintenance matters.',
  ],
  [
    'building-management-attendance',
    'Building Management Attendance',
    'attendance',
    ['strata-building'],
    60,
    24,
    'Arrange on-site operational support for shared building areas.',
  ],
  [
    'maintenance-attendance',
    'Maintenance Attendance',
    'maintenance',
    all,
    45,
    24,
    'Assess and document a reported maintenance issue to support the next decision.',
  ],
  [
    'completed-works-inspection',
    'Completed Works Inspection',
    'maintenance',
    all,
    30,
    24,
    'Photograph completed repairs and record their apparent completion.',
  ],
  [
    'follow-up-reinspection',
    'Follow-Up / Reinspection',
    'maintenance',
    all,
    30,
    24,
    'Revisit previously identified matters and document their current condition.',
  ],
  [
    'damage-incident-inspection',
    'Damage / Incident Inspection',
    'inspections',
    ['strata-building'],
    45,
    12,
    'Document visible damage and affected common-property areas for further review.',
  ],
  [
    'cleaning-presentation-inspection',
    'Cleaning & Presentation Inspection',
    'inspections',
    ['strata-building'],
    30,
    24,
    'Review common-area presentation and document cleaning matters.',
  ],
  [
    'defect-rectification-inspection',
    'Defect / Rectification Inspection',
    'maintenance',
    ['strata-building'],
    60,
    24,
    'Record apparent defects and the status of identified rectification items.',
  ],
  [
    'property-meeting',
    'Property Meeting',
    'attendance',
    all,
    30,
    24,
    'Meet an authorised owner, manager or contractor at the property.',
  ],
  [
    'contractor-access-attendance',
    'Contractor Access Attendance',
    'access',
    all,
    60,
    24,
    'Facilitate authorised contractor access and record the attendance.',
  ],
  [
    'key-handover-collection',
    'Key / Fob / Remote Handover',
    'access',
    all,
    30,
    24,
    'Coordinate an authorised collection, delivery or access-device handover.',
  ],
  [
    'contractor-supervision-attendance',
    'Contractor Supervision Attendance',
    'access',
    ['strata-building'],
    60,
    24,
    'Provide agreed operational attendance while contractors carry out work.',
  ],
  [
    'move-in-move-out-attendance',
    'Move-In / Move-Out Attendance',
    'access',
    ['strata-building'],
    60,
    48,
    'Coordinate agreed building access and common-area requirements for a move.',
  ],
  [
    'urgent-building-attendance',
    'Urgent Building Attendance',
    'attendance',
    ['strata-building'],
    60,
    0,
    'Request assessment of an urgent on-site attendance need, subject to availability.',
  ],
  [
    'building-handover-attendance',
    'Building Handover Attendance',
    'attendance',
    ['strata-building'],
    90,
    48,
    'Support an operational handover between authorised building representatives.',
  ],
  [
    'other-custom-appointment',
    'Custom Property Attendance',
    'attendance',
    all,
    60,
    24,
    'Discuss an on-site property task that falls outside the standard catalogue.',
  ],
];
export const SERVICE_SEEDS: Service[] = rows.map(
  ([id, name, family, sectors, duration_minutes, notice_hours, summary]) => ({
    id,
    name,
    family,
    sectors,
    duration_minutes,
    notice_hours,
    summary,
    buffer_before: 15,
    buffer_after: 15,
    horizon_days: 60,
    price_ex_gst_cents: null,
    booking_mode: 'request',
    active: 1,
  }),
);
export function findService(id: string) {
  return SERVICE_SEEDS.find((service) => service.id === id);
}
