import { createRequestHandler } from 'react-router';
// @ts-expect-error Generated by the React Router build plugin.
const handle = createRequestHandler(() => import('virtual:react-router/server-build'), import.meta.env.MODE);
export default {
  async fetch(request: Request, env: Record<string,string>, ctx: ExecutionContext) {
    if (new URL(request.url).pathname === '/api/health') return Response.json({ok:true,application:'marketing',environment:env.APP_ENV,source:env.BUILD_SHA});
    return handle(request, {cloudflare:{env,ctx}});
  },
};
