import { createRequestHandler, RouterContextProvider } from 'react-router';
import { runtimeContext } from '../../../packages/database/context';
// @ts-expect-error Generated by the React Router build plugin.
const handle = createRequestHandler(
  () => import('virtual:react-router/server-build'),
  import.meta.env.MODE,
);
export default {
  async fetch(request: Request, env: Record<string, string>, ctx: ExecutionContext) {
    if (new URL(request.url).pathname === '/api/health')
      return Response.json({
        ok: true,
        application: 'marketing',
        environment: env.APP_ENV,
        source: env.BUILD_SHA,
      });
    const context = new RouterContextProvider();
    context.set(runtimeContext, { env, ctx, nonce: btoa(crypto.randomUUID()) });
    const response = await handle(request, context);
    const headers = new Headers(response.headers);
    headers.set('X-Content-Type-Options', 'nosniff');
    headers.set('Referrer-Policy', 'strict-origin-when-cross-origin');
    headers.set('X-Frame-Options', 'DENY');
    return new Response(response.body, { status: response.status, headers });
  },
};
